theme = "space-villain"
icons = "awesome5"
scrolling = "natural"


[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "backlight"
device = "amdgpu_bl0"

#[[block]]
#block = "bluetooth"
#mac = "A0:8A:F5:B8:01:FD"
#label = " Rowkin"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "prev", "next"]

[[block]]
block = "sound"
#format = "{output_name} {volume}"
format = "{output_description} {volume}"
step_width = 1
[block.mappings]
"alsa_output.usb-Logitech_G560_Gaming_Speaker_00000000-00.analog-stereo" = "🔈"
"alsa_output.pci-0000_04_00.6.analog-stereo" = "🎧"

#[[block]]
#block = "speedtest"
#bytes = true
#interval = 1800

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} {signal_strength} {speed_up} {speed_down}"
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0


[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

#[[block]]
#block = "temperature"
#collapsed = false
#interval = 10
#format = "{min} min, {max} max, {average} avg"
#chip = "*-isa-*"
#inputs = ["CPUTIN", "SYSTIN"]

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 1
format = "%A, %B %d %H:%M:%S"
