theme = "space-villain"
icons = "awesome5"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "pomodoro"
length = 25
break_length = 5
message = "Take a break!"
break_message = "Back to work!"
use_nag = true
nag_path = "i3-nagbar"

#[[block]]
#block = "bluetooth"
#mac = "A0:8A:F5:B8:01:FD"
#label = " Rowkin"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "sound"
format = "{output_name} {volume}"
step_width = 1
[block.mappings]
"alsa_output.usb-Logitech_G560_Gaming_Speaker_00000000-00.analog-stereo" = "🔈"
"alsa_output.pci-0000_00_1b.0.analog-stereo" = "🎧"

#[[block]]
#block = "speedtest"
#bytes = true
#interval = 1800

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} {signal_strength} {ip} {speed_down} {graph_down}"
interval = 5
use_bits = false

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "nvidia_gpu"
label = "GTX 1060"
show_memory = true
show_clocks = true
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"
chip = "*-isa-*"
inputs = ["CPUTIN", "SYSTIN"]


#[[block]]
#block = "pacman"
#interval = 600
#format = "{pacman} + {aur} = {both} updates available"
#format_singular = "{both} update available"
#format_up_to_date = "system up to date"
#critical_updates_regex = "(linux |linux-lts|linux-zen)"
## aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
#aur_command = "pikaur -Qua"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "time"
interval = 1
format = "%A, %B %d %H:%M:%S"
