---
- name: Harden SSH
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^#PermitRootLogin', line: 'PermitRootLogin no' }
    - { regexp: '^#PasswordAuthentication', line: 'PasswordAuthentication no'}
  notify:
    - reload sshd
